version: '2.2'

services:
  syslog:
    image: 722249479844.dkr.ecr.us-east-1.amazonaws.com/rsyslog-kafka:${VERSION:-latest}
    build:
      context: .
      args:
        - VERSION
        - BUILD_DATE
        - http_proxy
        - https_proxy
        - ftp_proxy
        - no_proxy
        - DISABLE_YUM_MIRROR
    environment:
      - TZ
      - rsyslog_omkafka_enabled=on
      - rsyslog_omkafka_broker=["gilfoyle:9092"]
      - rsyslog_omkafka_topic=syslog
      - rsyslog_omkafka_dynaTopic=off
      - rsyslog_mmjsonparse=on
      - rsyslog_omfile_enabled=off
      - rsyslog_support_metadata_formats=on
      - rsyslog_omkafka_template=TmplJSONMsgAndRawMsg
    volumes:
      - syslog_log:/var/log/remote
      - syslog_work:/var/lib/rsyslog
      - syslog_tls:/etc/pki/rsyslog
    stop_grace_period: 1m30s
    mem_limit: 16g
    cap_add:
      - SYS_NICE

volumes:
  syslog_log:
  syslog_work:
  syslog_tls:
